### ISSUE TITLE
"e.map is not a function" error on time series

### ISSUE THREAD

**Issue by robert-digit** [airbnb/superset#2687]
Since upgrading to 0.17.5, and now on 0.17.6 alpha1, I get "TypeError: e.map is not a function" in the dev console when trying to generate a line series. 

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.5 and 0.17.6 alpha 1

### Expected results
Time series chart renders

### Actual results
An empty viz area and this stacktrace in the dev console. Unfortunately the JS is minified.
```
explorev2.0.17.6-alpha.1.entry.js:144 Uncaught TypeError: e.map is not a function
    at explorev2.0.17.6-alpha.1.entry.js:144
    at r.utils.state.a (explorev2.0.17.6-alpha.1.entry.js:144)
    at r.utils.state.update (explorev2.0.17.6-alpha.1.entry.js:144)
    at SVGSVGElement.<anonymous> (explorev2.0.17.6-alpha.1.entry.js:144)
    at explorev2.0.17.6-alpha.1.entry.js:34
    at $ (explorev2.0.17.6-alpha.1.entry.js:34)
    at Array.ql.each (explorev2.0.17.6-alpha.1.entry.js:34)
    at Array.e (explorev2.0.17.6-alpha.1.entry.js:144)
    at Array.Oa.call (explorev2.0.17.6-alpha.1.entry.js:34)
    at Object.b [as generate] (explorev2.0.17.6-alpha.1.entry.js:39)
```

### Steps to reproduce
Try to create a time series chart in recent versions of Firefox or Chromium/Chrome using 0.17.5 or 0.17.6 alpha1

Note- it looks like e.map is defined just a bit earlier as seen in the screenshots here.

<img width="589" alt="screen shot 2017-04-27 at 14 39 55" src="https://cloud.githubusercontent.com/assets/20124307/25492055/bd202ff2-2b69-11e7-9e02-181bc55e5223.png">
<img width="592" alt="screen shot 2017-04-27 at 14 40 10" src="https://cloud.githubusercontent.com/assets/20124307/25492054/bd1d34aa-2b69-11e7-89d9-1e75375459ce.png">

**Comment by robert-digit** [comment]
Incidentally, if I can set a flag to build without minifying I'll do that and check it out.

**Comment by Georgepentaho** [comment]
I have encountered same issues, waiting for solution！

**Comment by jeffcarey** [comment]
Is this still an issue? I couldn't reproduce it on current master (targeting 0.18.0-alpha.4). Regarding the note, I think that is just the result of the minifier using "e" as the name for both the array and the argument to the map function.

**Comment by mistercrunch** [comment]
You get this on all time series line charts? Including the examples we ship with? Anything special about your environment?

**Comment by zhouhoo** [comment]
I use latest version，but this issue is still there!

**Comment by williamdrake** [comment]
I'm getting this issue when trying to load graphs from the Explore function from SQL Lab.

**Comment by afilipchik** [comment]
Getting it as well. Any idea on how to fix it?

**Comment by jjal** [comment]
We're seeing it too. Occurs when doing graphs from SQL Lab > Explore. Doesn't happen when creating graphs directly from Charts

**Comment by christophlingg** [comment]
when I refresh the page, the js error is gone

**Comment by jjal** [comment]
Oh cool, that works here too.
